### ISSUE TITLE
Rust - Support http2

### ISSUE THREAD

**Issue by Morganamilo** [ably/ably-rust#22]
reqwest already supports this but needs the feature `native-tls-alpn` which may not work on older operating systems (>3 years old?).

Another way is to use the rust tls backend instead of the system one with the `rustls` feature.

The best way to do this is probably to  enable `native-tls-alpn` by default and have features for the other options if the user needs them.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-2381) by [Unito](https://www.unito.io)

**Comment by lmars** [comment]
> The best way to do this is probably to enable native-tls-alpn by default and have features for the other options if the user needs them.

This sounds like a good approach to me.
